### ISSUE TITLE
404 not found with à running app instead of swagger

### ISSUE THREAD

**Issue by guigz3r** [OpenClassrooms-Student-Center/G-rez-l-int-gration-continue-avec-Git-et-scripts#1]
Hello @hector-lachambre , 

Can you please confirm everything is working fine on your side ? 

When I compose up the project environment everything seems to be running ok: 
![image](https://github.com/user-attachments/assets/3f89c158-204c-48b0-b4ad-d112e93d5a4b)

But only get 404 instead of expected display. 
![image](https://github.com/user-attachments/assets/11d8e50e-d4ad-4986-8279-78849a5871bb)

Regards

**Comment by hector-lachambre** [comment]
Hi @guigz3r

I see in the screenshot that the application's WAR package has been placed in the /usr/local/tomcat/webapps/workshop-organizer-0.2.4.war location in the Docker image. 

![image](https://github.com/user-attachments/assets/bf94b019-6db8-4acc-8374-c1c06c486628)

If you want to access the application via / (http://localhost:8080/), the package needs to be moved to /usr/local/tomcat/webapps/ROOT.war.

You can find documentation at https://tomcat.apache.org/tomcat-9.0-doc/config/context.html

Please, tell me if you encounter any other problems.
